server:
  address: 127.0.0.1
  port: 8080
  servlet:
    session:
      timeout: 5m

spring:
  application:
    name: powercine

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  artemis:
    user: ${ARTEMIS_USERNAME}
    password: ${ARTEMIS_PASSWORD}
    broker-url: ${ARTEMIS_BROKER_URL}

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

    jdbc:
      dialect: mysql


logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug
    jakarta.jms: debug
