server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      timeout: 5m

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: powercine

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  session:
    redis:
      flush-mode: on_save
      namespace: spring:session

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug


powercine:
  env:
    frontendapp:
      endpoint: "${FRONTEND_ENDPOINT}"

    minioapp:
      endpoint: "${MINIO_ENDPOINT}"
      username: "${MINIO_ACCESS_KEY}"
      password: "${MINIO_SECRET_KEY}"

    oauth2:
      redirect: "${powercine.env.frontendapp.endpoint}/callback"

    current:
      host: "192.168.1.103"