server:
  address: 127.0.0.1
  port: 8080
  servlet:
    session:
      timeout: 5m

spring:
  application:
    name: powercine

  datasource:
    url: "jdbc:h2:mem:movienationdb;DB_CLOSE_ON_EXIT=FALSE"
    username: "piter"
    password: "piter"
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

  #session:
  #  redis:
  #    flush-mode: on_save
  #    namespace: spring:session

  #cache:
  #  type: redis

  #data:
  #  redis:
  #    host: localhost
  #    port: 6379


logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug
